run:
  tests: false
linters:
  enable:
    - asasalint
    - contextcheck
    - cyclop
    - dupl
    - errorlint
    - copyloopvar
    - funlen
    - gocritic
    - gocognit
    - gocyclo
    - gosec
    - govet
    - gosimple
    - staticcheck
    - unused
    - prealloc
    - revive
    - unconvert
    - unparam
    - usestdlibvars
